# Starship default config, extracted from the source


# Configure the format of the prompt
format = """\
        $username\
        $hostname\
        $shlvl\
        $singularity\
        $kubernetes\
        $directory\
        $git_branch\
        $git_commit\
        $git_state\
        $git_status\
        $hg_branch\
        $docker_context\
        $package\
        (‚Üì Toolchain version modules ‚Üì)\
        $cmake\
        $dart\
        $dotnet\
        $elixir\
        $elm\
        $erlang\
        $golang\
        $helm\
        $java\
        $julia\
        $nim\
        $nodejs\
        $ocaml\
        $perl\
        $php\
        $purescript\
        $python\
        $ruby\
        $rust\
        $swift\
        $terraform\
        $zig\
        (‚Üë Toolchain version modules ‚Üë)\
        $nix_shell\
        $conda\
        $memory_usage\
        $aws\
        $gcloud\
        $env_var\
        $crystal\
        $cmd_duration\
        $custom\
        (‚Üë above input line ‚Üë)\
        $line_break\
        (‚Üì on input line ‚Üì)\
        $jobs\
        $battery\
        $time\
        $status\
        $character\
    """


# Timeout for starship to scan files (in milliseconds)
scan_timeout = 30

# Add a new line before the start of the prompt
add_newline = true

palette = "catppuccin_mocha"

[aws]
disabled = false
format = 'on [$symbol$profile(\($region\))]($style) '
symbol = "ÓåΩ "
style = "bold yellow"

[battery]
disabled = true
full_symbol = "Ôï∏"
charging_symbol = "ÔñÉ"
discharging_symbol = "ÔñÇ"
format = "[$symbol$percentage]($style) "
[[battery.display]]
threshold = 10
style = "red bold"

[character]
disabled = false
format = "$symbol "
success_symbol = "[‚ùØ](bold green)"
error_symbol = "[‚ùØ](bold red)"
# vicmd_symbol = "[‚ùÆ](bold green)"

[cmake]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Ô®∂ "
style = "bold blue"

[cmd_duration]
disabled = false
min_time = 2_000
format = "took [$duration]($style) "
show_milliseconds = false
style = "yellow bold"
show_notifications = false
min_time_to_notify = 45_000

[conda]
disabled = false
truncation_length = 1
format = "via [$symbol$environment]($style) "
symbol = "ÔÑå "
style = "green bold"
ignore_base = true

[crystal]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Ôàô "
style = "bold red"

[dart]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Óûò "
style = "bold blue"

[directory]
disabled = false
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "cyan bold"
read_only = "Ô†Ω"
read_only_style = "red"
truncation_symbol = ""

# [directory.substitutions]
# "/path/to/replace" = "string/symbol"

[docker_context]
disabled = false
symbol = "Ôåà "
style = "blue bold"
format = "via [$symbol$context]($style) "
only_with_files = true

[dotnet]
disabled = false
format = "[$symbol$version( üéØ $tfm)]($style) "
symbol = "‚Ä¢NET "
style = "blue bold"
heuristic = true

[elixir]
disabled = false
format = 'via [$symbol$version \(OTP $otp_version\)]($style) '
symbol = "Óâµ "
style = "bold purple"

[elm]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Óò¨ "
style = "cyan bold"

[env_var]
# disabled = false
# symbol = ""
# style = "black bold dimmed"
# variable = ""
# default = ""
# format = "with [$env_value]($style) "

[erlang]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Óû± "
style = "bold red"

[gcloud]
disabled = false
format = 'on [$symbol$account(\($region\))]($style) '
symbol = "ÓåΩ "
style = "bold blue"

[git_branch]
disabled = false
format = "on [$symbol$branch]($style) "
symbol = "Ôêò "
style = "bold red"
# truncation_length = 7 # default = 2^63 - 1
truncation_symbol = "‚Ä¶"

[git_commit]
disabled = false
commit_hash_length = 7
format = '[\($hash\)]($style) '
style = "green bold"
only_detached = true

[git_state]
disabled = false
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "red bold"
stashed = '\$'
ahead = "‚á°"
behind = "‚á£"
diverged = "‚áï"
conflicted = "="
deleted = "‚úò"
renamed = "¬ª"
modified = "!"
staged = "+"
untracked = "?"

[golang]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Óòß "
style = "bold cyan"

[helm]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "‚éà "
style = "bold white"

[hostname]
disabled = false
ssh_only = true
trim_at = "."
format = "[$hostname]($style) in "
style = "flamingo dimmed bold"

[java]
disabled = false
format = "via [$symbol$version]($style) "
style = "red dimmed"
symbol = "Óâñ "

[jobs]
disabled = false
threshold = 1
format = "[$symbol$number]($style) "
symbol = "‚ú¶"
style = "bold blue"

[julia]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Óò§ "
style = "bold purple"

[kubernetes]
disabled = true
symbol = "‚ò∏ "
format = '[$symbol$context( \($namespace\))]($style) in '
style = "cyan bold"

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = 75
format = "via $symbol[$ram( | $swap)]($style) "
style = "white bold dimmed"
symbol = "Ô°ö "

# Mercurial
[hg_branch]
disabled = false
symbol = "Ôêò "
style = "bold purple"
format = "on [$symbol$branch]($style) "
# truncation_length = 8 # default = 2^63 - 1
truncation_symbol = "‚Ä¶"

[nim]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Ôö§ "
style = "yellow bold"

[nix_shell]
disabled = false
format = 'via [$symbol$state( \($name\))]($style) '
symbol = "Ôãú  "
style = "bold blue"
impure_msg = "impure"
pure_msg = "pure"

[nodejs]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Ó¥ç "
style = "bold green"

[ocaml]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "üê´ "
style = "bold yellow"

[package]
disabled = false
format = "is [$symbol$version]($style) "
symbol = "Ó¨© "
style = "peach bold"
display_private = false

[perl]
disabled = false
symbol = "Óù© "
style = "149 bold"
format = "via [$symbol$version]($style) "

[php]
disabled = false
symbol = "Óòà "
style = "147 bold"
format = "via [$symbol$version]($style) "

[purescript]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "<=> "
style = "bold white"

[python]
disabled = false
pyenv_version_name = false
pyenv_prefix = "pyenv "
python_binary = "python"
# scan_for_pyfiles = true
format = 'via [${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '
style = "yellow bold"
symbol = "ÓòÜ "

[ruby]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "Óàæ "
style = "bold red"

[rust]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "ÔÄì "
style = "bold red"

[shlvl]
disabled = true
threshold = 2
format = "[$symbol$shlvl]($style) "
symbol = "‚Üï"
style = "bold yellow"

[singularity]
disabled = false
format = '[$symbol\[$env\]]($style) '
symbol = ""
style = "blue bold dimmed"

[swift]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "ÔØ£ "
style = "bold 202"

[status]
disabled = true
format = "[$symbol$status]($style) "
symbol = "‚úñ"
style = "bold red"

[terraform]
disabled = false
format = "via [$symbol$workspace]($style) "
symbol = "Ô∞â "
style = "bold 105"

[time]
disabled = true
format = "at [$time]($style) "
style = "bold yellow"
use_12hr = false
time_format = ""
utc_time_offset = "local"
time_range = "-"

[username]
disabled = false
format = "[$user]($style) in "
style_root = "teal bold"
style_user = "teal bold"
show_always = true

[zig]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "‚ÜØ "
style = "bold yellow"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
